apiVersion: apps/v1
kind: Deployment
metadata: 
  name: vote
  namespace: instavote
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 3
  revisionHistoryLimit: 4
  paused: false
  minReadySeconds: 20
  selector: 
    matchLabels:
      role: vote
    matchExpressions:
      - {key: version, operator: In, values: [v1,v2,v3]}
  template:
    metadata:
      name: vote
      labels:
        app: python
        role: vote
        version: v1
    spec:
      containers:
        - name: app
          image: schoolofdevops/vote:v2
          envFrom:
            - configMapRef:
                name: vote
          ports:
            - containerPort: 80
              protocol: TCP 
