apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    role: vote 
spec:
  selector:
    role: vote
    version: v1
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
  externalIPs: 
    - 54.152.214.121
