apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: instavote
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  minReadySeconds: 20
  selector:
    matchLabels:
      role: worker
    matchExpressions:
      - {key: version, operator: In, values: [v1,v2,v3]}
  template:
    metadata:
      name: worker
      labels:
        app: java
        role: worker
        version: v2
    spec:
      containers:
        - name: app
          image: schoolofdevops/worker:v2
